# Generated by Django 5.1.7 on 2025-05-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_token"),
        ("lists", "0007_list_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="shared_lists",
            field=models.ManyToManyField(
                blank=True, related_name="shared_with", to="lists.list"
            ),
        ),
    ]
